# Generated by Django 2.1.2 on 2019-12-04 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.EmailField(default=None, max_length=10)),
                ('Dept_id', models.CharField(default=None, max_length=10)),
                ('Dept_name', models.CharField(default=None, max_length=10)),
                ('profile_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.EmailField(default='shadow@gmail.com', max_length=254)),
                ('Dept_id', models.CharField(default='123', max_length=50)),
                ('Dept_name', models.CharField(choices=[('Department of consumer affairs', 'Department of consumer affairs'), ('Department of food and public distribution', 'Department of food and public distribution'), ('Serious Fraud Investigation Office', 'Serious Fraud Investigation Office'), ('Forest Reserve Conservation Authority', 'Forest Reserve Conservation Authority'), ('Criminal Investigation Department', 'Criminal Investigation Department'), ('Labour Beauro', 'Labour Beauro'), ('National Commission for Minorities', 'National Commission for Minorities'), ('National Commission for Women', 'National Commission for Women'), ('Incometax Department', 'Incometax Department')], default='Incometax Department', max_length=50)),
                ('profile_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email_id', models.EmailField(default='shadow@gmail.com', max_length=254)),
                ('Dept_id', models.CharField(default='123', max_length=50)),
                ('Dept_name', models.CharField(default='BBC', max_length=50)),
                ('profile_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.CharField(default='Not Specified', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
