# Generated by Django 2.1.2 on 2019-12-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='Email_id',
            field=models.EmailField(default='shadow@gmail.com', max_length=254),
        ),
    ]
