# Generated by Django 2.1.2 on 2019-12-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191204_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='Dept_id',
            field=models.CharField(default='Ano', max_length=10),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='Dept_name',
            field=models.CharField(default='ano', max_length=10),
        ),
    ]
